<a href="https://colab.research.google.com/github/vinaydonthojuaiml/tensforflow-developer-certification/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

# More specifically, we're going to cover:
 * Introduction to tensors
 * Getting information from tensors
 * Manipulating tensors
 * Tensors & Numpy
 * Using @tf.function (a way to speed up your regular python functions)
 * Using GPUs with Tensorflow (or TPUs)
 * Excerises



# Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [4]:
# Create tensors with tf.constant()
#control + shift +space for description
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim



0

In [7]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check the dimension of our vector
vector.ndim

1

In [12]:
# Create a matrix  ( has more than 1 dimension)

matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [13]:
# # Check the dimension of our matrix
matrix.ndim

2

In [15]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype = tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [16]:
another_matrix.ndim

2

In [25]:
# let's create the tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                       [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [26]:
tensor.ndim

3

# WHat we've created so far:
 * Scalar : a single number
 * Vector: a number with direction (e.g. wind sppend and direction)
 * Matrix : a 2 dimensional array of numbers
 * Tensor: a n-dimensional array of numbers ( where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector